import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import Router from 'next/router'
import { getInstagramData } from '../lib/instadata'



export default function Home({data}) {
  
  useEffect(() => {

    
  
  }, [data])
  console.log(data)
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       hello
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

// export async function getServerSideProps (context) {
  // console.log("context", context.req)
  // let data = null
  // if (context.req.cookies.accessTokenAPI) {
  //   const token = JSON.parse(context.req.cookies.accessTokenAPI)
  //   data = await getInstagramData(token)
  // }
//   return {props:{}}
// }
