import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import Router from 'next/router'
import { getInstagramData } from '../lib/instadata'



export default function Home({data}) {
  
  useEffect(() => {

    
  
  }, [data])
  console.log(data)
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       hello
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

// export async function getStaticProps () {
//   const data = {home: "HOME "}
//   // const ig = new Instagram()
//   // const user = await setUser()
//   // const userFeed = insta.ig.feed.user(insta.user);
//   // const myPostsFirstPage = await userFeed.items();
  

//   return {
//     props: { home: data.home }
//   }
// }

export async function getServerSideProps (context) {
  console.log("context",)
  const token = JSON.parse(context.req.cookies.accessTokenAPI)

  const data = await getInstagramData(token)
  console.log(data)

  // console.log(userFeed)
  // return {
  //   redirect: {
  //     destination: auth.url,
  //     permanent: false,
  //   }
  // }
  return {props:{data: data}}
}
